import './globals.css'
import type { Metadata } from 'next'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul>
            <li className='left'>
              <Link className='nav-link' href='/'>Login</Link>
            </li>
            <li className='left'>
              <Link className='nav-link' href='/hugo'>Hugo</Link>
            </li>
            <li className='left'>
              <Link className='nav-link' href='/vilma'>Vilma</Link>
            </li>
          </ul>
        </nav>
        <div className='child'>
          {children}
        </div>
      </body>
    </html>
  )
}
